when:
  - event: push
    branch: main

steps:
  - name: format
    image: ziglings/zig
    commands:
      - echo "Formatting code"
      - zig fmt .

  - name: test
    image: ziglings/zig
    commands:
      - echo "Running tests"
      - zig build test

  - name: build
    image: ziglings/zig
    commands:
      - echo "Starting build"
      - zig build