name: Zig CI

on:
  push:
    branches:
      - main

jobs:
  zig-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Install zig
        run: |
          curl https://www.zvm.app/install.sh
          zvm i master

      - name: Check out repo code
        uses: actions/checkout@v4

      - name: format
        run: |
          echo "Formatting code"
          zig fmt .

      - name: test
        run: |
          echo "Running tests"
          zig build test

      - name: build
        run: |
          echo "Starting build"
          zig build
